### ISSUE TITLE
Update transfer UI on mobile

### ISSUE THREAD

**Issue by Orestasas** [qubic/explorer-frontend#105]
Currently, the collapsed view of transfer on mobile looks like this:
![image](https://github.com/qubic/explorer-frontend/assets/59179809/a5de1eaf-8175-43bd-a8ca-3cc6e368d678)

We should update it based [on this design
](https://www.figma.com/design/uTkCAs5q8c1UiV9PPPRGcS/Qubic-apps?node-id=1674-638&t=mOFJbgPvsr5s3mjX-4)

Also, "Show entity reports from random peers" button should be renamed to "Show Entity Reports". Color of the button should be #808B9B

**Comment by konan-5** [comment]
Sorry, I've just fixed
