### ISSUE TITLE
Address page UI updates

### ISSUE THREAD

**Issue by Orestasas** [qubic/explorer-frontend#107]
1. To make explorer more user friendly we need to show $ value under balance
2. Update font sizes - address (18px to 16px),  balance (32px to 36px)
3. Update "show entity reports" button to only icon (next to balance)
4. Make TX status badge in transaction pill smaller
5. Increase transaction pill corner radius from 8px to 12px

Exact design can be [seen here](https://www.figma.com/design/uTkCAs5q8c1UiV9PPPRGcS/Qubic-apps?node-id=1735-47&t=X1ZchzldBWDL9HhS-4)

**Comment by AndyQus** [comment]
this issue will be closed
