### ISSUE TITLE
UI tweaks

### ISSUE THREAD

**Issue by Orestasas** [qubic/explorer-frontend#110]
1. On There should be 0 margin on transaction pills (see image)
2. Tabs font should be Space Grotesk
3. on mobile font size of the balance should be 24px
4. On transaction pills font size should be 16px on both address and amount
5. Font weight for balance should be medium, now it's regular
<img width="967" alt="image" src="https://github.com/qubic/explorer-frontend/assets/59179809/76953f84-79bd-46ad-b53f-567fc6a073df">
<img width="796" alt="image" src="https://github.com/qubic/explorer-frontend/assets/59179809/6d11e12c-562e-4557-8b14-3aa5b0dec00f">

**Comment by AndyQus** [comment]
this issue will be closed
