### ISSUE TITLE
Home page UI updates

### ISSUE THREAD

**Issue by Orestasas** [qubic/explorer-frontend#113]
We should update corner radius of all containers from 8px to 12px
We should update icons to new ones ( [source](https://www.figma.com/design/uTkCAs5q8c1UiV9PPPRGcS/Qubic-apps?node-id=1861-480&t=Tsx0Vret7U6Oc77h-4) )
<img width="1091" alt="image" src="https://github.com/qubic/explorer-frontend/assets/59179809/8987d570-149b-4aed-b10b-ae0f90c7722d">

**Comment by AndyQus** [comment]
this issue will be closed
