### ISSUE TITLE
Address explorer: To use archive services from v2 and to display the timestamp information in the trx cell

### ISSUE THREAD

**Issue by sallymoc** [qubic/explorer-frontend#159]
1. To update trx related services calls to v2 and to display the timestamp information

i.e https://explorer.qubic.org/network/address/YUSSEWQMXJQFUEOKXISNUHUWEQQDVMLXQBWUDZDNRDSJDIHOHQRPINUFDBFJ

is making many calls to service
https://rpc.qubic.org/v1/identities/YUSSEWQMXJQFUEOKXISNUHUWEQQDVMLXQBWUDZDNRDSJDIHOHQRPINUFDBFJ/transfer-transactions?startTick=6489984&endTick=6589984 
with different range of ticks
and also to

https://rpc.qubic.org/v1/tx-status/TRX_ID
for each transaction to be displayed in the app.

In v2, there is the service /v2/identities/{identity}/transfers
it's available and it returns as part of the results the timestamp and the status of the transaction (no need to call v1/tx-status/TRX_ID anymore per transaction).

2. To display the timestamp for each transaction.

Please see issue https://github.com/qubic/explorer-frontend/issues/148 that is related to the same screen, maybe can be worked together.

**Comment by alexmf91** [comment]
done in https://github.com/qubic/explorer-frontend/pull/160

**Comment by sallymoc** [comment]
Live version is already using endpoing v2 for the transfers in the identity.
Also, displaying the timestamp and tick number.
Checking the Figma, format proposed for the timestamp field it's different than the solution, but we can open a separated ticket for this.
