### ISSUE TITLE
To remove Data Status field

### ISSUE THREAD

**Issue by sallymoc** [qubic/explorer-frontend#173]
Data Status field was part of the qubic.li services as per solution design reasons.

1. This field is not used anymore in qubic.org services so please remove it from tick details page.
2. For empty ticks, instead of displaying data incomplete, the Tick Status field should be displayed with value "Empty"

Current:
![image](https://github.com/user-attachments/assets/8118dc83-f34f-4a93-bbd4-bf63b22e5405)

**Comment by alexmf91** [comment]
@sallymoc Fixed after migrating tickpage to archiver endpoints and enhance the UI

**Comment by sallymoc** [comment]
@alexmf91 where should I try this? I see in dev, staging and production "Data Status" field still displayed in the tick page for empty and non empty ticks

**Comment by sallymoc** [comment]
Moving back to "Ready" because is not done yet.

**Comment by sallymoc** [comment]
This is solved and deployed in production Version 1.11.0
