### ISSUE TITLE
Some transactions are not shown in the entity view

### ISSUE THREAD

**Issue by qubicmio** [qubic/explorer-frontend#204]
For example

* https://explorer.qubic.org/network/tx/tnkgunguufierbczfkamgwswcqjdlofafkshokwycbqpuncturrsyoedpuff
* https://explorer.qubic.org/network/tx/toovnynelrcbtaahbzswurfmshqcunupowbqlmtikbwkkefngzliytsgtvuk

These are not shown here:
* https://explorer.qubic.org/network/address/CDROLFAERZLIJADTFEJJBDDZYCQDRBUHULUDSHCDVBOXFMQMXIDVVPTDNOVF

![Screenshot_2024-12-13_09-02-18](https://github.com/user-attachments/assets/be8a6202-f0ac-4f47-bcee-05d91ce113b6)

These are smart contract transactions (QX).

**Comment by sallymoc** [comment]
I agree with you @mio this is a bug.
I opened couple of months ago https://github.com/qubic/explorer-frontend/issues/148 that explana the same.

**Comment by sallymoc** [comment]
Closing as duplication for ticket https://github.com/qubic/explorer-frontend/issues/148
