### ISSUE TITLE
Small design updates

### ISSUE THREAD

**Issue by Orestasas** [qubic/explorer-frontend#31]
1. Clicking on qubic explorer logo should bring to a homepage
2. Space between header and containers should be 32px
![image](https://github.com/qubic/explorer-frontend/assets/59179809/d11badae-e5f6-47ab-9d62-5a1da93b2273)
3. Transaction container should have same background as other containers (gray80)
![image](https://github.com/qubic/explorer-frontend/assets/59179809/78c84001-9495-46a0-aa78-5ebb6a0de4b3)

**Comment by konan-5** [comment]
Updated all
