### ISSUE TITLE
The site should support the following languages

### ISSUE THREAD

**Issue by AndyQus** [qubic/explorer-frontend#36]
- en
- de
- es
- fr
- nl
- pt
- ru
- chinese (new)
- japan (?)

analogous to the one in the wallet
https://github.com/qubic/wallet/tree/main/src/assets/i18n

**Comment by AndyQus** [comment]
prepare all save files. I speak to different people using their native language. I got the names.

**Comment by konan-5** [comment]
I've set up an environment for multiple languages. If we have all the source files for each language, the multilanguage feature will work.

**Comment by AndyQus** [comment]
[pt.txt](https://github.com/qubic/explorer-frontend/files/14795803/pt.txt)

**Comment by AndyQus** [comment]
[fr.txt](https://github.com/qubic/explorer-frontend/files/14795960/fr.txt)

**Comment by AndyQus** [comment]
[ru.txt](https://github.com/qubic/explorer-frontend/files/14796078/ru.txt)

**Comment by AndyQus** [comment]
[es.txt](https://github.com/qubic/explorer-frontend/files/14796160/es.txt)

**Comment by AndyQus** [comment]
[zh.txt](https://github.com/qubic/explorer-frontend/files/14804155/zh.txt)

**Comment by konan-5** [comment]
Added all source files and Implemented localstorage.
