### ISSUE TITLE
Incorrect display of value in address

### ISSUE THREAD

**Issue by AndyQus** [qubic/explorer-frontend#40]
I noticed something while testing.
The new Explorer always has the value: 1 QUBIC
https://betaexplorer.qubic.org/network/address/BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARMID
I think the correct value is not yet displayed here.

Here is the current explorer:
https://app.qubic.li/network/explorer/address/BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARMID

It is the ID of the asset pool QX.
![image](https://github.com/qubic/explorer-frontend/assets/157237454/81cca723-a993-4eae-9b82-34055ea204c8)
![image](https://github.com/qubic/explorer-frontend/assets/157237454/7821a47d-01ae-4e84-96aa-41d76ac3fd09)

**Comment by konan-5** [comment]
from reportedValue
incomingAmount - outgoingAmount
