### ISSUE TITLE
Use a list of API calls that we are currently using in Explorer.

### ISSUE THREAD

**Issue by AndyQus** [qubic/explorer-frontend#72]
- we need it to switch to the archiver

**Comment by rain-coin** [comment]
https://docs.google.com/document/d/1GPpmxwIuzdLqjsOwxYzUuwzwsOkuhYIctb1-JsfaNIQ/edit?usp=sharing

**Comment by konan-5** [comment]
first, for list of api calls in new explorer I used google docs.
@0xluk what do you need more?

https://docs.google.com/document/d/1GPpmxwIuzdLqjsOwxYzUuwzwsOkuhYIctb1-JsfaNIQ/edit?usp=sharing

**Comment by 0xluk** [comment]
@konan-5 can you give me some search examples that you are performing on `/Search/Query/` ?

**Comment by konan-5** [comment]
@0xluk I've updated above google docs about search example.
is it enough for you?
