### ISSUE TITLE
Arabic language file received, it needs to be checked

### ISSUE THREAD

**Issue by AndyQus** [qubic/explorer-frontend#73]
the file is from user Kyoto, thanks 
[ar.json](https://github.com/qubic/explorer-frontend/files/15011777/ar.json)

**Comment by AndyQus** [comment]
[ar.json](https://github.com/qubic/explorer-frontend/files/15059853/ar.json)
Please use this file. It has been checked and changed by elwess.

**Comment by konan-5** [comment]
got it, will implement soon

**Comment by AndyQus** [comment]
`const locale = {
  pageNotFound: 'الصفحة غير موجودة',
  error404Message: 'تهانينا! أنت أحد النخبة الذين تمكنوا من العثور على صفحتنا 404',
  backToHomePage: 'العودة إلى الصفحة الرئيسية'
};
export default locale;

**Comment by konan-5** [comment]
ty @AndyQus
