### ISSUE TITLE
Include link https://status.qubic.li/ in Explorer "Network Status"

### ISSUE THREAD

**Issue by AndyQus** [qubic/explorer-frontend#74]
Idee from kyoto

@Orestasas Do you have an idea we could incorporate it? Kyoto made the suggestion to include it in the footer. Unfortunately, you can't see it right away. Maybe to the right of search? With symbol.

**Comment by Orestasas** [comment]
![image](https://github.com/qubic/explorer-frontend/assets/59179809/48ba5e94-4895-4451-9f6f-597f3d92f48d)
@AndyQus yes, in the header could work.

**Comment by AndyQus** [comment]
in footer

**Comment by konan-5** [comment]
I also think footer is better

**Comment by AndyQus** [comment]
@Orestasas Just for your information, I also included a link in the wallet.
![image](https://github.com/qubic/explorer-frontend/assets/157237454/04c6f796-99c8-49b5-8683-545892a75ffd)

**Comment by konan-5** [comment]
ty @AndyQus  @Orestasas
