### ISSUE TITLE
When you enter the website, it should be displayed in the language of the browser.

### ISSUE THREAD

**Issue by AndyQus** [qubic/explorer-frontend#76]

**Comment by konan-5** [comment]
@AndyQus I am not sure what you mean

**Comment by AndyQus** [comment]
in angular wallet:
  ngOnInit(): void {
    if (Object.keys(this.supportedLanguagesDictionary).includes(this.browserLanguage)) {
      this.selected = this.browserLanguage;
    } else {
      this.selected = 'en';
    }
    this.translocoService.setActiveLang(this.selected);
  }

**Comment by AndyQus** [comment]
When you open the page, the language should be preselected. The page should be displayed in the language that is also the default language of the browser.
