### ISSUE TITLE
Show the tick and date at TX

### ISSUE THREAD

**Issue by AndyQus** [qubic/explorer-frontend#79]
annotation joetom

![image](https://github.com/qubic/explorer-frontend/assets/157237454/dab42096-296e-4dd9-a310-516199903326)

@Orestasas you can create a suggestion for the design.

**Comment by AndyQus** [comment]
![image](https://github.com/qubic/explorer-frontend/assets/157237454/113d87ce-f4e5-47c3-80f0-f180da08844e)

**Comment by alexmf91** [comment]
Solved in #160

**Comment by sallymoc** [comment]
The timestamp and tick number are displayed in the trx cell in the address explorer screen and trx details screen
However, checking the Figma, format proposed for the timestamp field it's different than the solution, but we can open a separated ticket for this.
