### ISSUE TITLE
Banner BETA remove, when....

### ISSUE THREAD

**Issue by AndyQus** [qubic/explorer-frontend#81]
@Orestasas you can add this paragraph on qubic.org, for all language files?

New paragraph on qubic.org under TOS

7.1 Explorer + Wallet
The Explorer (https://explorer.qubic.org/) and Wallet (https://wallet.qubic.org/) services are provided "as is". The data displayed may not be complete, especially for older transactions. Please always refer to your Wallet's balance provided by your own computer (full node) to ensure that you own a certain amount of Qubic or Assets.

when this is done, the "Beta" banner can be removed 
![grafik](https://github.com/qubic/explorer-frontend/assets/157237454/159a4319-1da9-4ea5-874d-007a7aa61998)

**Comment by konan-5** [comment]
@AndyQus  so can I remove banner rn?

**Comment by AndyQus** [comment]
Yes!

**Comment by konan-5** [comment]
Thank you !
